### ISSUE TITLE
Apple M1 arm64-simulator support

### ISSUE THREAD

**Issue by orbitekk** [Synerise/ios-sdk#146]
Hello, I'm using Apple M1 chip and I have compilation problem. This framework doesn't support arm64 architecture for simulator. Is it possible to recompile this framework with arm64 support?

### SDK Version

3.10.0

### What did you do?

Integrating SyneriseSDK with Cocoapods

## What did you expect to happen?

Run SyneriseSDK on arm64 simulator

## What happened instead?

Missing architecture arm64-simulator

**Comment by tajchert** [comment]
Please take a look at this - it is very important for us.

**Comment by awoczek** [comment]
Hello, thank you for feedback.

We will provide approach in early may.

**Comment by wojciech-kulik** [comment]
+1

**Comment by awoczek** [comment]
Yes, It is in progress. Please, last one moment.

**Comment by awoczek** [comment]
Synerise SDK version 4.2.0 is distributed as XCFramework and it is compatible for M1.
