### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by orbitekk** [Synerise/ios-sdk#147]
Hello!
I'm going to switch my project from CocoaPods to SPM. Could you provide SPM support?

**Comment by awoczek** [comment]
We are planning it for Q2/2022.

**Comment by lukasz-szyszkowski** [comment]
Hi, it's almost 2024 still no SPM suppor? It's a shame.

**Comment by awoczek** [comment]
Thank you for long patience. It is done in 4.14.10 version.
