### ISSUE TITLE
Can't find synerise requests in Proxyman app

### ISSUE THREAD

**Issue by lukasz-szyszkowski** [Synerise/ios-sdk#187]
I wonder how I can determine if the Synerise SDK is sending data to the backend. I've tried to "catch" it in Proxyman, which is my usual method for other SDKs (like Firebase, Newrelic etc.), but I see nothing. There are no requests to your API.

I'm aware that a flush is executed every 5 seconds by default, and I can see logs in the Xcode console when I turn ﻿debug mode on in the SDK. So 

here are my questions:
	a.	Why can't I see these requests?
	b.	How can I confirm the SDK is working properly?

**Comment by awoczek** [comment]
Hello,
The sdk implements protection against MiTM attacks and that's the reason of this behavior.

**Comment by awoczek** [comment]
I see you sent 7 events. These aren't appeared on Synerise dashboard in your profile?

**Comment by lukasz-szyszkowski** [comment]
If it's here, I can't see anything new. I've checked API key and I even generated new one with full permission. 
The board has no events from mobile app.
I'm running app directly from Xcode (debug mode), but I've also checked with app from TestFlight.
![CleanShot 2024-02-06 at 16 28 10@2x](https://github.com/Synerise/ios-sdk/assets/47628502/124033d0-2d7f-4a0c-8ac4-a4f9a65722b3)

**Comment by awoczek** [comment]
When you open application, do you see `client.applicationStarted` event? It should be appeared on the profile/dashboard after= the app started.

**Comment by lukasz-szyszkowski** [comment]
Sorry for delay, it started working a couple of days ago. To be honest, don't know why? 🤷‍♂️ Because I changed nothing in my code. 
I'm closing this Issue now, thanks for paying attention.

**Comment by lukasz-szyszkowski** [comment]
AFAIK I've tried it with and without proxy enabled.
