### ISSUE TITLE
Request to Rename Package to Resolve Namespace Conflicts

### ISSUE THREAD

**Issue by lukaszgieraltowski** [Synerise/ios-sdk#193]
Hello Synerise Team,

I have encountered a namespace conflict in my Swift project due to the generic naming of your SDK as `ios-sdk`. This common naming convention has led to conflicts with other packages, such as Phrase SDK, which also uses the same package identifier.

In order to resolve this issue and to avoid similar issues for other developers integrating your SDK alongside other packages, could you consider renaming your package to something more unique, such as `synerise-ios-sdk`? This change would not only resolve my current issue but also help in clearly differentiating your package within the Swift ecosystem.

Thank you for considering this request. I look forward to your response and a possible update to the package naming.

Best regards,
Lukas

**Comment by awoczek** [comment]
Hello @lukaszgieraltowski

We migrated repo to https://github.com/synerise/synerise-ios-sdk, so from the SDK version 4.17.1, the problem with package name conflict is resolved.

Thank you for your patience.
