### ISSUE TITLE
Marketing Consent

### ISSUE THREAD

**Issue by lukasz-szyszkowski** [Synerise/ios-sdk#195]
Hi, is there any way to let user set marketing consent using SDK? 
I mean, something similar to Firebase Analytics
```
Analytics.setConsent([
.analyticsStorage: .granted,
.adStorage: .granted,
.adUserData: .granted,
.adPersonalization: .granted,
])
```

**Comment by awoczek** [comment]
Hey @lukasz-szyszkowski , can you create issue on the ne repo here - https://github.com/Synerise/synerise-ios-sdk?

**Comment by awoczek** [comment]
The issue will be moved to https://github.com/Synerise/synerise-ios-sdk
